### ISSUE TITLE
Read Version

### ISSUE THREAD

**Issue by staerz** [johnthagen/doxygen-junit#4]
Hello,

I'm using your tool in our setup and as a validity check, I always run "<tool> -v" or "<tool> --version" to get the version of the tool I'm using to make sure there's everything as expected.

Unfortunately, neither the option "-v" nor "--version" are available options for doxygen_junit.

Could you please add it?

**Comment by johnthagen** [comment]
Fixed in 0d7c4feeaf65f9032ccf53b64ea9ea094f16f22a. Please try v2.1.0.

**Comment by staerz** [comment]
Thanks for adding this feature so quickly!
